# Generated by Django 4.2.5 on 2023-09-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='kyc/')),
                ('uploaded_on', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DeliveryOrder',
        ),
    ]
