# Generated by Django 4.2.5 on 2023-09-22 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_deliverykyc_delete_deliveryorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryKYC',
        ),
    ]
