services:
  ecom:
    build:
      context: ./backend
      # dockerfile: backend/Dockerfile.dev
    command: >
      sh -c "python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py init_admin &&
        python manage.py runserver 0.0.0.0:8001"
    
    volumes:
      - ./backend:/usr/src/ecom
    expose:
      - 8001
    ports:
      - 80:8001
      - 8001:8001
    hostname: ecomhost
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./backend/.env.dev

  db:
    image: postgres:16-alpine3.18
    restart: always
    environment:
      POSTGRES_DB: ecomdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ecomtoolssecret
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - 5432
    hostname: db

  # cache:
  #   image: redis:7-alpine
  #   restart: always
  #   ports:
  #     - '6379:6379'
  #   command: redis-server --save 20 1 --loglevel warning --requirepass devtoolssecret
  #   volumes: 
  #     - cache:/data

  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@tachyonbyte.com
  #     PGADMIN_DEFAULT_PASSWORD: devsecret
  #     PGADMIN_LISTEN_PORT: 80
  #   ports:
  #     - "8085:80"
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  #   links:
  #     - "dbgis:pgisql-server"

volumes:
  db-data:
  # pgadmin-data:
  # cache:
  #   driver: local