# Generated by Django 4.2.5 on 2023-09-27 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellerProduct',
        ),
    ]
