# Generated by Django 4.2.5 on 2023-09-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_kyc'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='doc_type',
            field=models.CharField(choices=[('aadhar', 'aadhar'), ('pan', 'pan'), ('passport', 'passport'), ('driving_license', 'driving_license')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyc',
            name='kyc_status',
            field=models.BooleanField(default=False),
        ),
    ]
