# Generated by Django 4.2.5 on 2023-09-27 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_kyc_doc_type_kyc_kyc_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='user',
        ),
    ]
