# Generated by Django 4.2.8 on 2024-01-02 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='status',
        ),
    ]
