# Generated by Django 4.2.7 on 2023-11-21 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('order', '0002_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='delivered_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='from_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='from_address', to='common.address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipping',
            name='shipping_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='to_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='to_address', to='common.address'),
            preserve_default=False,
        ),
    ]
