# Generated by Django 4.2.8 on 2024-01-03 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_shipping_delivered_on_shipping_from_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping',
            old_name='shipping_date',
            new_name='shipped_on',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='order',
            name='review',
        ),
    ]
