# Generated by Django 4.2.8 on 2024-01-03 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_address_user_address_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address',
            new_name='street_address',
        ),
        migrations.RemoveField(
            model_name='bankdetail',
            name='branch_name',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
