# Generated by Django 4.2.5 on 2023-09-21 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_type',
            field=models.CharField(choices=[('wishlist', 'wishlist'), ('cart', 'cart')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('pickup', 'pickup'), ('delivery', 'delivery')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.coupon'),
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
